// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/web/upload/handler.proto

package web_upload

import (
	fmt "fmt"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	proto "google.golang.org/protobuf/proto"
	math "math"
	http "net/http"
)

import (
	context "context"
	client "go-micro.dev/v5/client"
	metadata "go-micro.dev/v5/metadata"
	registry "go-micro.dev/v5/registry"
	server "go-micro.dev/v5/server"
	wb "go-micro.dev/v5/web"
	httputil "net/http/httputil"
	textproto "net/textproto"
	url "net/url"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ registry.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for UploadService service

func NewUploadServiceEndpoints() []*registry.Endpoint {
	return []*registry.Endpoint{
		{
			Authorization: false,
			Scope:         "",
			Name:          "UploadService.Activitys",
			Path:          "/Activitys",
			Method:        "POST",
			Handler:       "web",
		},
	}
}

// Client API for UploadService service

type UploadService interface {
	Activitys(ctx context.Context, w http.ResponseWriter, r *http.Request)
}

type uploadService struct {
	c    client.Client
	name string
}

func NewUploadService(name string, c client.Client) UploadService {
	return &uploadService{
		c:    c,
		name: name,
	}
}

func (c *uploadService) Activitys(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	next, err := c.c.Options().Selector.Select(c.name)
	if err != nil {
		return
	}
	s, err := next()
	if err != nil {
		return
	}
	service := fmt.Sprintf("http://%s", s.Address)
	if len(service) == 0 {
		w.WriteHeader(404)
		return
	}
	rp, err := url.Parse(service)
	if err != nil {
		w.WriteHeader(500)
		return
	}
	httputil.NewSingleHostReverseProxy(rp).ServeHTTP(w, r)
}

// Server API for UploadService service

type UploadServiceHandler interface {
	Activitys(context.Context, http.ResponseWriter, *http.Request)
}

func RegisterUploadServiceHandler(s wb.Service, hdlr UploadServiceHandler, opts ...wb.Option) {
	opts = append(opts, wb.Endpoint(&registry.Endpoint{
		Authorization: false,
		Scope:         "",
		Name:          "UploadService.Activitys",
		Path:          "/Activitys",
		Method:        "POST",
		Handler:       "web",
	}))
	s.Init(opts...)
	s.HandleFunc("/Activitys", func(w http.ResponseWriter, r *http.Request) {
		cx := r.Context()
		md, ok := metadata.FromContext(cx)
		if !ok {
			md = make(metadata.Metadata)
		}
		for k, v := range r.Header {
			md[textproto.CanonicalMIMEHeaderKey(k)] = strings.Join(v, ", ")
		}
		md["Host"] = r.Host
		if r.URL != nil {
			md["URL"] = r.URL.String()
		}
		cx = metadata.NewContext(cx, md)
		hdlr.Activitys(cx, w, r)
	})
}

type uploadServiceHandler struct {
	UploadServiceHandler
}

func (h *uploadServiceHandler) Activitys(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	h.UploadServiceHandler.Activitys(ctx, w, r)
}
