// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/auth/handler.proto

package auth

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "go-micro.dev/v5/client"
	registry "go-micro.dev/v5/registry"
	server "go-micro.dev/v5/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ registry.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for AuthService service

func NewAuthServiceEndpoints() []*registry.Endpoint {
	return []*registry.Endpoint{}
}

// Client API for AuthService service

type AuthService interface {
	Generate(ctx context.Context, in *Account, opts ...client.CallOption) (*Token, error)
	Inspect(ctx context.Context, in *Token, opts ...client.CallOption) (*Account, error)
	Verify(ctx context.Context, in *Credential, opts ...client.CallOption) (*Empty, error)
	Refresh(ctx context.Context, in *Token, opts ...client.CallOption) (*Token, error)
}

type authService struct {
	c    client.Client
	name string
}

func NewAuthService(name string, c client.Client) AuthService {
	return &authService{
		c:    c,
		name: name,
	}
}

func (c *authService) Generate(ctx context.Context, in *Account, opts ...client.CallOption) (*Token, error) {
	req := c.c.NewRequest(c.name, "AuthService.Generate", in)
	out := new(Token)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) Inspect(ctx context.Context, in *Token, opts ...client.CallOption) (*Account, error) {
	req := c.c.NewRequest(c.name, "AuthService.Inspect", in)
	out := new(Account)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) Verify(ctx context.Context, in *Credential, opts ...client.CallOption) (*Empty, error) {
	req := c.c.NewRequest(c.name, "AuthService.Verify", in)
	out := new(Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) Refresh(ctx context.Context, in *Token, opts ...client.CallOption) (*Token, error) {
	req := c.c.NewRequest(c.name, "AuthService.Refresh", in)
	out := new(Token)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AuthService service

type AuthServiceHandler interface {
	Generate(context.Context, *Account, *Token) error
	Inspect(context.Context, *Token, *Account) error
	Verify(context.Context, *Credential, *Empty) error
	Refresh(context.Context, *Token, *Token) error
}

func RegisterAuthServiceHandler(s server.Server, hdlr AuthServiceHandler, opts ...server.HandlerOption) error {
	type authService interface {
		Generate(ctx context.Context, in *Account, out *Token) error
		Inspect(ctx context.Context, in *Token, out *Account) error
		Verify(ctx context.Context, in *Credential, out *Empty) error
		Refresh(ctx context.Context, in *Token, out *Token) error
	}
	type AuthService struct {
		authService
	}
	h := &authServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&AuthService{h}, opts...))
}

type authServiceHandler struct {
	AuthServiceHandler
}

func (h *authServiceHandler) Generate(ctx context.Context, in *Account, out *Token) error {
	return h.AuthServiceHandler.Generate(ctx, in, out)
}

func (h *authServiceHandler) Inspect(ctx context.Context, in *Token, out *Account) error {
	return h.AuthServiceHandler.Inspect(ctx, in, out)
}

func (h *authServiceHandler) Verify(ctx context.Context, in *Credential, out *Empty) error {
	return h.AuthServiceHandler.Verify(ctx, in, out)
}

func (h *authServiceHandler) Refresh(ctx context.Context, in *Token, out *Token) error {
	return h.AuthServiceHandler.Refresh(ctx, in, out)
}
