// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/web/fileupload/handler.proto

package web_fileupload

import (
	fmt "fmt"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	proto "google.golang.org/protobuf/proto"
	math "math"
	http "net/http"
)

import (
	context "context"
	client "go-micro.dev/v5/client"
	registry "go-micro.dev/v5/registry"
	server "go-micro.dev/v5/server"
	wb "go-micro.dev/v5/web"
	httputil "net/http/httputil"
	url "net/url"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ registry.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for FileUploadService service

func NewFileUploadServiceEndpoints() []*registry.Endpoint {
	return []*registry.Endpoint{
		{
			Authorization: false,
			Scope:         "",
			Name:          "FileUploadService.Upload",
			Path:          "/upload",
			Method:        "POST",
			Handler:       "web",
		},
	}
}

// Client API for FileUploadService service

type FileUploadService interface {
	Upload(ctx context.Context, w http.ResponseWriter, r *http.Request)
}

type fileUploadService struct {
	c    client.Client
	name string
}

func NewFileUploadService(name string, c client.Client) FileUploadService {
	return &fileUploadService{
		c:    c,
		name: name,
	}
}

func (c *fileUploadService) Upload(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	next, err := c.c.Options().Selector.Select(c.name)
	if err != nil {
		return
	}
	s, err := next()
	if err != nil {
		return
	}
	service := fmt.Sprintf("http://%s", s.Address)
	if len(service) == 0 {
		w.WriteHeader(404)
		return
	}
	rp, err := url.Parse(service)
	if err != nil {
		w.WriteHeader(500)
		return
	}
	httputil.NewSingleHostReverseProxy(rp).ServeHTTP(w, r)
}

// Server API for FileUploadService service

type FileUploadServiceHandler interface {
	Upload(context.Context, http.ResponseWriter, *http.Request)
}

func RegisterFileUploadServiceHandler(s wb.Service, hdlr FileUploadServiceHandler, opts ...wb.Option) {
	opts = append(opts, wb.Endpoint(&registry.Endpoint{
		Authorization: false,
		Scope:         "",
		Name:          "FileUploadService.Upload",
		Path:          "/upload",
		Method:        "POST",
		Handler:       "web",
	}))
	s.Init(opts...)
	s.HandleFunc("/upload", func(w http.ResponseWriter, r *http.Request) {
		cx := r.Context()
		hdlr.Upload(cx, w, r)
	})
}

type fileUploadServiceHandler struct {
	FileUploadServiceHandler
}

func (h *fileUploadServiceHandler) Upload(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	h.FileUploadServiceHandler.Upload(ctx, w, r)
}
