// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/test/handler.proto

package test

import (
	fmt "fmt"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "go-micro.dev/v5/client"
	registry "go-micro.dev/v5/registry"
	server "go-micro.dev/v5/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ registry.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for TestService service

func NewTestServiceEndpoints() []*registry.Endpoint {
	return []*registry.Endpoint{
		{
			Authorization: false,
			Scope:         "test",
			Name:          "TestService.ListWeather",
			Path:          "/ListWeather",
			Method:        "GET",
			Handler:       "rpc",
		},
	}
}

// Client API for TestService service

type TestService interface {
	ListWeather(ctx context.Context, in *Empty, opts ...client.CallOption) (*Empty, error)
}

type testService struct {
	c    client.Client
	name string
}

func NewTestService(name string, c client.Client) TestService {
	return &testService{
		c:    c,
		name: name,
	}
}

func (c *testService) ListWeather(ctx context.Context, in *Empty, opts ...client.CallOption) (*Empty, error) {
	req := c.c.NewRequest(c.name, "TestService.ListWeather", in)
	out := new(Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TestService service

type TestServiceHandler interface {
	ListWeather(context.Context, *Empty, *Empty) error
}

func RegisterTestServiceHandler(s server.Server, hdlr TestServiceHandler, opts ...server.HandlerOption) error {
	type testService interface {
		ListWeather(ctx context.Context, in *Empty, out *Empty) error
	}
	type TestService struct {
		testService
	}
	h := &testServiceHandler{hdlr}
	opts = append(opts, server.WithEndpoint(&registry.Endpoint{
		Authorization: false,
		Scope:         "test",
		Name:          "TestService.ListWeather",
		Path:          "/ListWeather",
		Method:        "GET",
		Handler:       "rpc",
	}))
	return s.Handle(s.NewHandler(&TestService{h}, opts...))
}

type testServiceHandler struct {
	TestServiceHandler
}

func (h *testServiceHandler) ListWeather(ctx context.Context, in *Empty, out *Empty) error {
	return h.TestServiceHandler.ListWeather(ctx, in, out)
}
