// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/proxy/handler.proto

package proxy

import (
	fmt "fmt"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "go-micro.dev/v5/client"
	registry "go-micro.dev/v5/registry"
	server "go-micro.dev/v5/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ registry.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for MicroService service

func NewMicroServiceEndpoints() []*registry.Endpoint {
	return []*registry.Endpoint{
		{
			Authorization: false,
			Scope:         "micro",
			Name:          "MicroService.Home",
			Path:          "/Home",
			Method:        "GET",
			Handler:       "rpc",
		},
	}
}

// Client API for MicroService service

type MicroService interface {
	Home(ctx context.Context, in *MicroFilter, opts ...client.CallOption) (*Micro, error)
}

type microService struct {
	c    client.Client
	name string
}

func NewMicroService(name string, c client.Client) MicroService {
	return &microService{
		c:    c,
		name: name,
	}
}

func (c *microService) Home(ctx context.Context, in *MicroFilter, opts ...client.CallOption) (*Micro, error) {
	req := c.c.NewRequest(c.name, "MicroService.Home", in)
	out := new(Micro)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MicroService service

type MicroServiceHandler interface {
	Home(context.Context, *MicroFilter, *Micro) error
}

func RegisterMicroServiceHandler(s server.Server, hdlr MicroServiceHandler, opts ...server.HandlerOption) error {
	type microService interface {
		Home(ctx context.Context, in *MicroFilter, out *Micro) error
	}
	type MicroService struct {
		microService
	}
	h := &microServiceHandler{hdlr}
	opts = append(opts, server.WithEndpoint(&registry.Endpoint{
		Authorization: false,
		Scope:         "micro",
		Name:          "MicroService.Home",
		Path:          "/Home",
		Method:        "GET",
		Handler:       "rpc",
	}))
	return s.Handle(s.NewHandler(&MicroService{h}, opts...))
}

type microServiceHandler struct {
	MicroServiceHandler
}

func (h *microServiceHandler) Home(ctx context.Context, in *MicroFilter, out *Micro) error {
	return h.MicroServiceHandler.Home(ctx, in, out)
}

// Api Endpoints for MeiZuService service

func NewMeiZuServiceEndpoints() []*registry.Endpoint {
	return []*registry.Endpoint{
		{
			Authorization: false,
			Scope:         "meizu",
			Name:          "MeiZuService.ListWeather",
			Path:          "/ListWeather",
			Method:        "GET",
			Handler:       "rpc",
		},
	}
}

// Client API for MeiZuService service

type MeiZuService interface {
	ListWeather(ctx context.Context, in *WeatherFilter, opts ...client.CallOption) (*WeatherList, error)
}

type meiZuService struct {
	c    client.Client
	name string
}

func NewMeiZuService(name string, c client.Client) MeiZuService {
	return &meiZuService{
		c:    c,
		name: name,
	}
}

func (c *meiZuService) ListWeather(ctx context.Context, in *WeatherFilter, opts ...client.CallOption) (*WeatherList, error) {
	req := c.c.NewRequest(c.name, "MeiZuService.ListWeather", in)
	out := new(WeatherList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MeiZuService service

type MeiZuServiceHandler interface {
	ListWeather(context.Context, *WeatherFilter, *WeatherList) error
}

func RegisterMeiZuServiceHandler(s server.Server, hdlr MeiZuServiceHandler, opts ...server.HandlerOption) error {
	type meiZuService interface {
		ListWeather(ctx context.Context, in *WeatherFilter, out *WeatherList) error
	}
	type MeiZuService struct {
		meiZuService
	}
	h := &meiZuServiceHandler{hdlr}
	opts = append(opts, server.WithEndpoint(&registry.Endpoint{
		Authorization: false,
		Scope:         "meizu",
		Name:          "MeiZuService.ListWeather",
		Path:          "/ListWeather",
		Method:        "GET",
		Handler:       "rpc",
	}))
	return s.Handle(s.NewHandler(&MeiZuService{h}, opts...))
}

type meiZuServiceHandler struct {
	MeiZuServiceHandler
}

func (h *meiZuServiceHandler) ListWeather(ctx context.Context, in *WeatherFilter, out *WeatherList) error {
	return h.MeiZuServiceHandler.ListWeather(ctx, in, out)
}
