// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4-devel
// 	protoc        v3.19.4
// source: proto/proxy/micro.proto

package proxy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MicroFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNo        int32                  `protobuf:"varint,1,opt,name=page_no,proto3" json:"page_no"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,proto3" json:"page_size"`
	OrderType     int32                  `protobuf:"varint,3,opt,name=order_type,proto3" json:"order_type"`
	OrderCol      string                 `protobuf:"bytes,4,opt,name=order_col,proto3" json:"order_col"`
	Id            int32                  `protobuf:"varint,5,opt,name=id,proto3" json:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MicroFilter) Reset() {
	*x = MicroFilter{}
	mi := &file_proto_proxy_micro_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MicroFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MicroFilter) ProtoMessage() {}

func (x *MicroFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proxy_micro_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MicroFilter.ProtoReflect.Descriptor instead.
func (*MicroFilter) Descriptor() ([]byte, []int) {
	return file_proto_proxy_micro_proto_rawDescGZIP(), []int{0}
}

func (x *MicroFilter) GetPageNo() int32 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *MicroFilter) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *MicroFilter) GetOrderType() int32 {
	if x != nil {
		return x.OrderType
	}
	return 0
}

func (x *MicroFilter) GetOrderCol() string {
	if x != nil {
		return x.OrderCol
	}
	return ""
}

func (x *MicroFilter) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Micro struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,8,opt,name=version,proto3" json:"version"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Micro) Reset() {
	*x = Micro{}
	mi := &file_proto_proxy_micro_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Micro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Micro) ProtoMessage() {}

func (x *Micro) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proxy_micro_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Micro.ProtoReflect.Descriptor instead.
func (*Micro) Descriptor() ([]byte, []int) {
	return file_proto_proxy_micro_proto_rawDescGZIP(), []int{1}
}

func (x *Micro) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_proto_proxy_micro_proto protoreflect.FileDescriptor

var file_proto_proxy_micro_proto_rawDesc = string([]byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x6d, 0x69,
	0x63, 0x72, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x93, 0x01, 0x0a, 0x0b, 0x4d, 0x69,
	0x63, 0x72, 0x6f, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x67,
	0x65, 0x5f, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x61, 0x67, 0x65,
	0x5f, 0x6e, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6c, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x21, 0x0a, 0x05, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x42, 0x09, 0x5a, 0x07, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_proxy_micro_proto_rawDescOnce sync.Once
	file_proto_proxy_micro_proto_rawDescData []byte
)

func file_proto_proxy_micro_proto_rawDescGZIP() []byte {
	file_proto_proxy_micro_proto_rawDescOnce.Do(func() {
		file_proto_proxy_micro_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proxy_micro_proto_rawDesc), len(file_proto_proxy_micro_proto_rawDesc)))
	})
	return file_proto_proxy_micro_proto_rawDescData
}

var file_proto_proxy_micro_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_proxy_micro_proto_goTypes = []any{
	(*MicroFilter)(nil), // 0: MicroFilter
	(*Micro)(nil),       // 1: Micro
}
var file_proto_proxy_micro_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_proxy_micro_proto_init() }
func file_proto_proxy_micro_proto_init() {
	if File_proto_proxy_micro_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proxy_micro_proto_rawDesc), len(file_proto_proxy_micro_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_proxy_micro_proto_goTypes,
		DependencyIndexes: file_proto_proxy_micro_proto_depIdxs,
		MessageInfos:      file_proto_proxy_micro_proto_msgTypes,
	}.Build()
	File_proto_proxy_micro_proto = out.File
	file_proto_proxy_micro_proto_goTypes = nil
	file_proto_proxy_micro_proto_depIdxs = nil
}
