// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4-devel
// 	protoc        v3.19.4
// source: proto/cron/cron.proto

package cron

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TimedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimedReq) Reset() {
	*x = TimedReq{}
	mi := &file_proto_cron_cron_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimedReq) ProtoMessage() {}

func (x *TimedReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cron_cron_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimedReq.ProtoReflect.Descriptor instead.
func (*TimedReq) Descriptor() ([]byte, []int) {
	return file_proto_cron_cron_proto_rawDescGZIP(), []int{0}
}

type TimedResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimedResp) Reset() {
	*x = TimedResp{}
	mi := &file_proto_cron_cron_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimedResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimedResp) ProtoMessage() {}

func (x *TimedResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cron_cron_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimedResp.ProtoReflect.Descriptor instead.
func (*TimedResp) Descriptor() ([]byte, []int) {
	return file_proto_cron_cron_proto_rawDescGZIP(), []int{1}
}

var File_proto_cron_cron_proto protoreflect.FileDescriptor

var file_proto_cron_cron_proto_rawDesc = string([]byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x72, 0x6f, 0x6e, 0x2f, 0x63, 0x72, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0a, 0x0a, 0x08, 0x54, 0x69, 0x6d, 0x65, 0x64,
	0x52, 0x65, 0x71, 0x22, 0x0b, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x42, 0x08, 0x5a, 0x06, 0x2f, 0x3b, 0x63, 0x72, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
})

var (
	file_proto_cron_cron_proto_rawDescOnce sync.Once
	file_proto_cron_cron_proto_rawDescData []byte
)

func file_proto_cron_cron_proto_rawDescGZIP() []byte {
	file_proto_cron_cron_proto_rawDescOnce.Do(func() {
		file_proto_cron_cron_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cron_cron_proto_rawDesc), len(file_proto_cron_cron_proto_rawDesc)))
	})
	return file_proto_cron_cron_proto_rawDescData
}

var file_proto_cron_cron_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_cron_cron_proto_goTypes = []any{
	(*TimedReq)(nil),  // 0: TimedReq
	(*TimedResp)(nil), // 1: TimedResp
}
var file_proto_cron_cron_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_cron_cron_proto_init() }
func file_proto_cron_cron_proto_init() {
	if File_proto_cron_cron_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cron_cron_proto_rawDesc), len(file_proto_cron_cron_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_cron_cron_proto_goTypes,
		DependencyIndexes: file_proto_cron_cron_proto_depIdxs,
		MessageInfos:      file_proto_cron_cron_proto_msgTypes,
	}.Build()
	File_proto_cron_cron_proto = out.File
	file_proto_cron_cron_proto_goTypes = nil
	file_proto_cron_cron_proto_depIdxs = nil
}
