// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/cron/cron.proto

package cron

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on TimedReq with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TimedReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TimedReq with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TimedReqMultiError, or nil
// if none found.
func (m *TimedReq) ValidateAll() error {
	return m.validate(true)
}

func (m *TimedReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return TimedReqMultiError(errors)
	}

	return nil
}

// TimedReqMultiError is an error wrapping multiple validation errors returned
// by TimedReq.ValidateAll() if the designated constraints aren't met.
type TimedReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TimedReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TimedReqMultiError) AllErrors() []error { return m }

// TimedReqValidationError is the validation error returned by
// TimedReq.Validate if the designated constraints aren't met.
type TimedReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TimedReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TimedReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TimedReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TimedReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TimedReqValidationError) ErrorName() string { return "TimedReqValidationError" }

// Error satisfies the builtin error interface
func (e TimedReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTimedReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TimedReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TimedReqValidationError{}

// Validate checks the field values on TimedResp with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TimedResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TimedResp with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TimedRespMultiError, or nil
// if none found.
func (m *TimedResp) ValidateAll() error {
	return m.validate(true)
}

func (m *TimedResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return TimedRespMultiError(errors)
	}

	return nil
}

// TimedRespMultiError is an error wrapping multiple validation errors returned
// by TimedResp.ValidateAll() if the designated constraints aren't met.
type TimedRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TimedRespMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TimedRespMultiError) AllErrors() []error { return m }

// TimedRespValidationError is the validation error returned by
// TimedResp.Validate if the designated constraints aren't met.
type TimedRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TimedRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TimedRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TimedRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TimedRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TimedRespValidationError) ErrorName() string { return "TimedRespValidationError" }

// Error satisfies the builtin error interface
func (e TimedRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTimedResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TimedRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TimedRespValidationError{}
