// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/cron/handler.proto

package cron

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "go-micro.dev/v5/client"
	registry "go-micro.dev/v5/registry"
	server "go-micro.dev/v5/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ registry.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for CronService service

func NewCronServiceEndpoints() []*registry.Endpoint {
	return []*registry.Endpoint{}
}

// Client API for CronService service

type CronService interface {
}

type cronService struct {
	c    client.Client
	name string
}

func NewCronService(name string, c client.Client) CronService {
	return &cronService{
		c:    c,
		name: name,
	}
}

// Server API for CronService service

type CronServiceHandler interface {
}

func RegisterCronServiceHandler(s server.Server, hdlr CronServiceHandler, opts ...server.HandlerOption) error {
	type cronService interface {
	}
	type CronService struct {
		cronService
	}
	h := &cronServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&CronService{h}, opts...))
}

type cronServiceHandler struct {
	CronServiceHandler
}
