// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/pushhub/handler.proto

package pushhub

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "go-micro.dev/v5/client"
	registry "go-micro.dev/v5/registry"
	server "go-micro.dev/v5/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ registry.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for PushhubService service

func NewPushhubServiceEndpoints() []*registry.Endpoint {
	return []*registry.Endpoint{}
}

// Client API for PushhubService service

type PushhubService interface {
}

type pushhubService struct {
	c    client.Client
	name string
}

func NewPushhubService(name string, c client.Client) PushhubService {
	return &pushhubService{
		c:    c,
		name: name,
	}
}

// Server API for PushhubService service

type PushhubServiceHandler interface {
}

func RegisterPushhubServiceHandler(s server.Server, hdlr PushhubServiceHandler, opts ...server.HandlerOption) error {
	type pushhubService interface {
	}
	type PushhubService struct {
		pushhubService
	}
	h := &pushhubServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&PushhubService{h}, opts...))
}

type pushhubServiceHandler struct {
	PushhubServiceHandler
}
