// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/apigate/handler.proto

package apigate

import (
	fmt "fmt"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	proto "google.golang.org/protobuf/proto"
	math "math"
	http "net/http"
)

import (
	context "context"
	client "go-micro.dev/v5/client"
	metadata "go-micro.dev/v5/metadata"
	registry "go-micro.dev/v5/registry"
	server "go-micro.dev/v5/server"
	wb "go-micro.dev/v5/web"
	httputil "net/http/httputil"
	textproto "net/textproto"
	url "net/url"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ registry.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ApigateService service

func NewApigateServiceEndpoints() []*registry.Endpoint {
	return []*registry.Endpoint{
		{
			Authorization: false,
			Scope:         "",
			Name:          "ApigateService.Home",
			Path:          "/",
			Method:        "GET",
			Handler:       "web",
		},
		{
			Authorization: false,
			Scope:         "",
			Name:          "ApigateService.Favicon",
			Path:          "/favicon.ico",
			Method:        "GET",
			Handler:       "web",
		},
	}
}

// Client API for ApigateService service

type ApigateService interface {
	Home(ctx context.Context, w http.ResponseWriter, r *http.Request)
	Favicon(ctx context.Context, w http.ResponseWriter, r *http.Request)
}

type apigateService struct {
	c    client.Client
	name string
}

func NewApigateService(name string, c client.Client) ApigateService {
	return &apigateService{
		c:    c,
		name: name,
	}
}

func (c *apigateService) Home(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	next, err := c.c.Options().Selector.Select(c.name)
	if err != nil {
		return
	}
	s, err := next()
	if err != nil {
		return
	}
	service := fmt.Sprintf("http://%s", s.Address)
	if len(service) == 0 {
		w.WriteHeader(404)
		return
	}
	rp, err := url.Parse(service)
	if err != nil {
		w.WriteHeader(500)
		return
	}
	httputil.NewSingleHostReverseProxy(rp).ServeHTTP(w, r)
}

func (c *apigateService) Favicon(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	next, err := c.c.Options().Selector.Select(c.name)
	if err != nil {
		return
	}
	s, err := next()
	if err != nil {
		return
	}
	service := fmt.Sprintf("http://%s", s.Address)
	if len(service) == 0 {
		w.WriteHeader(404)
		return
	}
	rp, err := url.Parse(service)
	if err != nil {
		w.WriteHeader(500)
		return
	}
	httputil.NewSingleHostReverseProxy(rp).ServeHTTP(w, r)
}

// Server API for ApigateService service

type ApigateServiceHandler interface {
	Home(context.Context, http.ResponseWriter, *http.Request)
	Favicon(context.Context, http.ResponseWriter, *http.Request)
}

func RegisterApigateServiceHandler(s wb.Service, hdlr ApigateServiceHandler, opts ...wb.Option) {
	opts = append(opts, wb.Endpoint(&registry.Endpoint{
		Authorization: false,
		Scope:         "",
		Name:          "ApigateService.Home",
		Path:          "/",
		Method:        "GET",
		Handler:       "web",
	}))
	opts = append(opts, wb.Endpoint(&registry.Endpoint{
		Authorization: false,
		Scope:         "",
		Name:          "ApigateService.Favicon",
		Path:          "/favicon.ico",
		Method:        "GET",
		Handler:       "web",
	}))
	s.Init(opts...)
	s.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		cx := r.Context()
		md, ok := metadata.FromContext(cx)
		if !ok {
			md = make(metadata.Metadata)
		}
		for k, v := range r.Header {
			md[textproto.CanonicalMIMEHeaderKey(k)] = strings.Join(v, ", ")
		}
		md["Host"] = r.Host
		if r.URL != nil {
			md["URL"] = r.URL.String()
		}
		cx = metadata.NewContext(cx, md)
		hdlr.Home(cx, w, r)
	})
	s.HandleFunc("/favicon.ico", func(w http.ResponseWriter, r *http.Request) {
		cx := r.Context()
		md, ok := metadata.FromContext(cx)
		if !ok {
			md = make(metadata.Metadata)
		}
		for k, v := range r.Header {
			md[textproto.CanonicalMIMEHeaderKey(k)] = strings.Join(v, ", ")
		}
		md["Host"] = r.Host
		if r.URL != nil {
			md["URL"] = r.URL.String()
		}
		cx = metadata.NewContext(cx, md)
		hdlr.Favicon(cx, w, r)
	})
}

type apigateServiceHandler struct {
	ApigateServiceHandler
}

func (h *apigateServiceHandler) Home(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	h.ApigateServiceHandler.Home(ctx, w, r)
}

func (h *apigateServiceHandler) Favicon(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	h.ApigateServiceHandler.Favicon(ctx, w, r)
}
