// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4-devel
// 	protoc        v3.19.4
// source: proto/dtm/busi.proto

package dtm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BusiReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Amount         int64                  `protobuf:"varint,1,opt,name=Amount,proto3" json:"Amount"`
	UserID         int64                  `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID"`
	TransOutResult string                 `protobuf:"bytes,3,opt,name=TransOutResult,proto3" json:"TransOutResult"`
	TransInResult  string                 `protobuf:"bytes,4,opt,name=TransInResult,proto3" json:"TransInResult"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BusiReq) Reset() {
	*x = BusiReq{}
	mi := &file_proto_dtm_busi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusiReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusiReq) ProtoMessage() {}

func (x *BusiReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtm_busi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusiReq.ProtoReflect.Descriptor instead.
func (*BusiReq) Descriptor() ([]byte, []int) {
	return file_proto_dtm_busi_proto_rawDescGZIP(), []int{0}
}

func (x *BusiReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BusiReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *BusiReq) GetTransOutResult() string {
	if x != nil {
		return x.TransOutResult
	}
	return ""
}

func (x *BusiReq) GetTransInResult() string {
	if x != nil {
		return x.TransInResult
	}
	return ""
}

type BusiReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BusiReply) Reset() {
	*x = BusiReply{}
	mi := &file_proto_dtm_busi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusiReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusiReply) ProtoMessage() {}

func (x *BusiReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtm_busi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusiReply.ProtoReflect.Descriptor instead.
func (*BusiReply) Descriptor() ([]byte, []int) {
	return file_proto_dtm_busi_proto_rawDescGZIP(), []int{1}
}

func (x *BusiReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_dtm_busi_proto protoreflect.FileDescriptor

var file_proto_dtm_busi_proto_rawDesc = string([]byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x74, 0x6d, 0x2f, 0x62, 0x75, 0x73, 0x69,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x87, 0x01, 0x0a, 0x07, 0x42, 0x75, 0x73, 0x69, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x26, 0x0a, 0x0e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x4f, 0x75, 0x74, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x49, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x49, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x25, 0x0a, 0x09, 0x42, 0x75, 0x73, 0x69, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a,
	0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x2f, 0x3b, 0x64, 0x74, 0x6d,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_dtm_busi_proto_rawDescOnce sync.Once
	file_proto_dtm_busi_proto_rawDescData []byte
)

func file_proto_dtm_busi_proto_rawDescGZIP() []byte {
	file_proto_dtm_busi_proto_rawDescOnce.Do(func() {
		file_proto_dtm_busi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dtm_busi_proto_rawDesc), len(file_proto_dtm_busi_proto_rawDesc)))
	})
	return file_proto_dtm_busi_proto_rawDescData
}

var file_proto_dtm_busi_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_dtm_busi_proto_goTypes = []any{
	(*BusiReq)(nil),   // 0: BusiReq
	(*BusiReply)(nil), // 1: BusiReply
}
var file_proto_dtm_busi_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_dtm_busi_proto_init() }
func file_proto_dtm_busi_proto_init() {
	if File_proto_dtm_busi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dtm_busi_proto_rawDesc), len(file_proto_dtm_busi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_dtm_busi_proto_goTypes,
		DependencyIndexes: file_proto_dtm_busi_proto_depIdxs,
		MessageInfos:      file_proto_dtm_busi_proto_msgTypes,
	}.Build()
	File_proto_dtm_busi_proto = out.File
	file_proto_dtm_busi_proto_goTypes = nil
	file_proto_dtm_busi_proto_depIdxs = nil
}
