// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/dtm/busi.proto

package dtm

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on BusiReq with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BusiReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BusiReq with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in BusiReqMultiError, or nil if none found.
func (m *BusiReq) ValidateAll() error {
	return m.validate(true)
}

func (m *BusiReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Amount

	// no validation rules for UserID

	// no validation rules for TransOutResult

	// no validation rules for TransInResult

	if len(errors) > 0 {
		return BusiReqMultiError(errors)
	}

	return nil
}

// BusiReqMultiError is an error wrapping multiple validation errors returned
// by BusiReq.ValidateAll() if the designated constraints aren't met.
type BusiReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BusiReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BusiReqMultiError) AllErrors() []error { return m }

// BusiReqValidationError is the validation error returned by BusiReq.Validate
// if the designated constraints aren't met.
type BusiReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BusiReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BusiReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BusiReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BusiReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BusiReqValidationError) ErrorName() string { return "BusiReqValidationError" }

// Error satisfies the builtin error interface
func (e BusiReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBusiReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BusiReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BusiReqValidationError{}

// Validate checks the field values on BusiReply with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BusiReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BusiReply with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BusiReplyMultiError, or nil
// if none found.
func (m *BusiReply) ValidateAll() error {
	return m.validate(true)
}

func (m *BusiReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	if len(errors) > 0 {
		return BusiReplyMultiError(errors)
	}

	return nil
}

// BusiReplyMultiError is an error wrapping multiple validation errors returned
// by BusiReply.ValidateAll() if the designated constraints aren't met.
type BusiReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BusiReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BusiReplyMultiError) AllErrors() []error { return m }

// BusiReplyValidationError is the validation error returned by
// BusiReply.Validate if the designated constraints aren't met.
type BusiReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BusiReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BusiReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BusiReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BusiReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BusiReplyValidationError) ErrorName() string { return "BusiReplyValidationError" }

// Error satisfies the builtin error interface
func (e BusiReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBusiReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BusiReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BusiReplyValidationError{}
