// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/dtm/handler.proto

package dtm

import (
	fmt "fmt"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "go-micro.dev/v5/client"
	registry "go-micro.dev/v5/registry"
	server "go-micro.dev/v5/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ registry.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for DtmService service

func NewDtmServiceEndpoints() []*registry.Endpoint {
	return []*registry.Endpoint{
		{
			Authorization: false,
			Scope:         "test",
			Name:          "DtmService.WorkflowGrpc",
			Path:          "/workflowGrpc",
			Method:        "GET",
			Handler:       "rpc",
		},
	}
}

// Client API for DtmService service

type DtmService interface {
	WorkflowGrpc(ctx context.Context, in *BusiReq, opts ...client.CallOption) (*BusiReply, error)
}

type dtmService struct {
	c    client.Client
	name string
}

func NewDtmService(name string, c client.Client) DtmService {
	return &dtmService{
		c:    c,
		name: name,
	}
}

func (c *dtmService) WorkflowGrpc(ctx context.Context, in *BusiReq, opts ...client.CallOption) (*BusiReply, error) {
	req := c.c.NewRequest(c.name, "DtmService.WorkflowGrpc", in)
	out := new(BusiReply)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DtmService service

type DtmServiceHandler interface {
	WorkflowGrpc(context.Context, *BusiReq, *BusiReply) error
}

func RegisterDtmServiceHandler(s server.Server, hdlr DtmServiceHandler, opts ...server.HandlerOption) error {
	type dtmService interface {
		WorkflowGrpc(ctx context.Context, in *BusiReq, out *BusiReply) error
	}
	type DtmService struct {
		dtmService
	}
	h := &dtmServiceHandler{hdlr}
	opts = append(opts, server.WithEndpoint(&registry.Endpoint{
		Authorization: false,
		Scope:         "test",
		Name:          "DtmService.WorkflowGrpc",
		Path:          "/workflowGrpc",
		Method:        "GET",
		Handler:       "rpc",
	}))
	return s.Handle(s.NewHandler(&DtmService{h}, opts...))
}

type dtmServiceHandler struct {
	DtmServiceHandler
}

func (h *dtmServiceHandler) WorkflowGrpc(ctx context.Context, in *BusiReq, out *BusiReply) error {
	return h.DtmServiceHandler.WorkflowGrpc(ctx, in, out)
}

// Api Endpoints for WorkflowService service

func NewWorkflowServiceEndpoints() []*registry.Endpoint {
	return []*registry.Endpoint{
		{
			Authorization: false,
			Scope:         "test",
			Name:          "WorkflowService.TransResume",
			Path:          "/transResume",
			Method:        "POST",
			Handler:       "rpc",
		},
		{
			Authorization: false,
			Scope:         "test",
			Name:          "WorkflowService.TransOut",
			Path:          "/transOut",
			Method:        "POST",
			Handler:       "rpc",
		},
		{
			Authorization: false,
			Scope:         "test",
			Name:          "WorkflowService.TransOutRevert",
			Path:          "/transOutRevert",
			Method:        "POST",
			Handler:       "rpc",
		},
		{
			Authorization: false,
			Scope:         "test",
			Name:          "WorkflowService.TransIn",
			Path:          "/transIn",
			Method:        "POST",
			Handler:       "rpc",
		},
		{
			Authorization: false,
			Scope:         "test",
			Name:          "WorkflowService.TransInRevert",
			Path:          "/transInRevert",
			Method:        "POST",
			Handler:       "rpc",
		},
	}
}

// Client API for WorkflowService service

type WorkflowService interface {
	TransResume(ctx context.Context, in *BusiReq, opts ...client.CallOption) (*BusiReply, error)
	TransOut(ctx context.Context, in *BusiReq, opts ...client.CallOption) (*BusiReply, error)
	TransOutRevert(ctx context.Context, in *BusiReq, opts ...client.CallOption) (*BusiReply, error)
	TransIn(ctx context.Context, in *BusiReq, opts ...client.CallOption) (*BusiReply, error)
	TransInRevert(ctx context.Context, in *BusiReq, opts ...client.CallOption) (*BusiReply, error)
}

type workflowService struct {
	c    client.Client
	name string
}

func NewWorkflowService(name string, c client.Client) WorkflowService {
	return &workflowService{
		c:    c,
		name: name,
	}
}

func (c *workflowService) TransResume(ctx context.Context, in *BusiReq, opts ...client.CallOption) (*BusiReply, error) {
	req := c.c.NewRequest(c.name, "WorkflowService.TransResume", in)
	out := new(BusiReply)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowService) TransOut(ctx context.Context, in *BusiReq, opts ...client.CallOption) (*BusiReply, error) {
	req := c.c.NewRequest(c.name, "WorkflowService.TransOut", in)
	out := new(BusiReply)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowService) TransOutRevert(ctx context.Context, in *BusiReq, opts ...client.CallOption) (*BusiReply, error) {
	req := c.c.NewRequest(c.name, "WorkflowService.TransOutRevert", in)
	out := new(BusiReply)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowService) TransIn(ctx context.Context, in *BusiReq, opts ...client.CallOption) (*BusiReply, error) {
	req := c.c.NewRequest(c.name, "WorkflowService.TransIn", in)
	out := new(BusiReply)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowService) TransInRevert(ctx context.Context, in *BusiReq, opts ...client.CallOption) (*BusiReply, error) {
	req := c.c.NewRequest(c.name, "WorkflowService.TransInRevert", in)
	out := new(BusiReply)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for WorkflowService service

type WorkflowServiceHandler interface {
	TransResume(context.Context, *BusiReq, *BusiReply) error
	TransOut(context.Context, *BusiReq, *BusiReply) error
	TransOutRevert(context.Context, *BusiReq, *BusiReply) error
	TransIn(context.Context, *BusiReq, *BusiReply) error
	TransInRevert(context.Context, *BusiReq, *BusiReply) error
}

func RegisterWorkflowServiceHandler(s server.Server, hdlr WorkflowServiceHandler, opts ...server.HandlerOption) error {
	type workflowService interface {
		TransResume(ctx context.Context, in *BusiReq, out *BusiReply) error
		TransOut(ctx context.Context, in *BusiReq, out *BusiReply) error
		TransOutRevert(ctx context.Context, in *BusiReq, out *BusiReply) error
		TransIn(ctx context.Context, in *BusiReq, out *BusiReply) error
		TransInRevert(ctx context.Context, in *BusiReq, out *BusiReply) error
	}
	type WorkflowService struct {
		workflowService
	}
	h := &workflowServiceHandler{hdlr}
	opts = append(opts, server.WithEndpoint(&registry.Endpoint{
		Authorization: false,
		Scope:         "test",
		Name:          "WorkflowService.TransResume",
		Path:          "/transResume",
		Method:        "POST",
		Handler:       "rpc",
	}))
	opts = append(opts, server.WithEndpoint(&registry.Endpoint{
		Authorization: false,
		Scope:         "test",
		Name:          "WorkflowService.TransOut",
		Path:          "/transOut",
		Method:        "POST",
		Handler:       "rpc",
	}))
	opts = append(opts, server.WithEndpoint(&registry.Endpoint{
		Authorization: false,
		Scope:         "test",
		Name:          "WorkflowService.TransOutRevert",
		Path:          "/transOutRevert",
		Method:        "POST",
		Handler:       "rpc",
	}))
	opts = append(opts, server.WithEndpoint(&registry.Endpoint{
		Authorization: false,
		Scope:         "test",
		Name:          "WorkflowService.TransIn",
		Path:          "/transIn",
		Method:        "POST",
		Handler:       "rpc",
	}))
	opts = append(opts, server.WithEndpoint(&registry.Endpoint{
		Authorization: false,
		Scope:         "test",
		Name:          "WorkflowService.TransInRevert",
		Path:          "/transInRevert",
		Method:        "POST",
		Handler:       "rpc",
	}))
	return s.Handle(s.NewHandler(&WorkflowService{h}, opts...))
}

type workflowServiceHandler struct {
	WorkflowServiceHandler
}

func (h *workflowServiceHandler) TransResume(ctx context.Context, in *BusiReq, out *BusiReply) error {
	return h.WorkflowServiceHandler.TransResume(ctx, in, out)
}

func (h *workflowServiceHandler) TransOut(ctx context.Context, in *BusiReq, out *BusiReply) error {
	return h.WorkflowServiceHandler.TransOut(ctx, in, out)
}

func (h *workflowServiceHandler) TransOutRevert(ctx context.Context, in *BusiReq, out *BusiReply) error {
	return h.WorkflowServiceHandler.TransOutRevert(ctx, in, out)
}

func (h *workflowServiceHandler) TransIn(ctx context.Context, in *BusiReq, out *BusiReply) error {
	return h.WorkflowServiceHandler.TransIn(ctx, in, out)
}

func (h *workflowServiceHandler) TransInRevert(ctx context.Context, in *BusiReq, out *BusiReply) error {
	return h.WorkflowServiceHandler.TransInRevert(ctx, in, out)
}
